version: '3.7'
services:
  elasticsearch:
    container_name: sqee_local
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
    networks:
      - sqee_local_network
  kibana:
    container_name: kb_kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    ports:
      - 5601:5601
    environment:
      XPACK_MONITORING_KIBANA_COLLECTION_ENABLED: 'true'
      ELASTICSEARCH_HOSTS: http://sqee_local:9200
    networks:
      - sqee_local_network
  apm:
    container_name: kb_apm
    image: docker.elastic.co/apm/apm-server:7.11.0
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=["sqee_local:9200"]
      - apm-server.secret_token=thisisasecret
      - monitoring.enabled=true
    networks:
      - sqee_local_network

networks:
  sqee_local_network: